### ISSUE TITLE
Update javax annotations in code and documentation to resolve compilation error on JDK 11, 17 and 21

### ISSUE THREAD

**Issue by TechnocratSid** [unitycatalog/unitycatalog#19] opened 2024-06-14 08:16 UTC
While attempting to build on JDK 11 following the [Compiling and testing guidelines](https://github.com/unitycatalog/unitycatalog?tab=readme-ov-file#compiling-and-testing), I encountered the error `cannot find symbol: class Generated in package javax.annotation`. 

To resolve this issue, I needed to update the annotations from `@javax.annotation.Generated` to `@javax.annotation.processing.Generated` 

We need to update our documentation/code to fix this issue.

**Comment by TechnocratSid** [comment] 2024-06-14 08:17
Tried with JDK 17 and got the same error.

**Comment by tdas** [comment] 2024-06-14 18:55
Can you post your exact jdk 11 version? From java -version?
Also what is the os?
I have seen this error in java 21, but has always worked for me on jdk11 and Mac.

**Comment by ray-harrison** [comment] 2024-06-15 21:49
I can confirm that with different versions of 11, 17 and 21, only the above noted change worked for me (annotation.Generated -> annotation.processing.Generated).

Versions: 11.0.23, 17.0.11, 21.0.3 (Corretto), Intel Mac (2019), Sonoma 14.5

**Comment by TechnocratSid** [comment] 2024-06-16 08:06
Yeah I've also tried with 11.0.11, 17.0.10 and 21.0.1 on M2 Mac, Sonoma 14.4.1. Got the error and resolved it by updating the javax annotations to `@javax.annotation.processing.Generated`

**Comment by codesorcery** [comment] 2024-06-17 17:35
Maybe also directly switch from `javax.annotation` to `jakarta.annotation`, since `javax.*` modules have been transitioned to `jakarta` back in 2020.
The client project already depends on `jakarta.annotation:jakarta.annotation-api` and the server project already uses `jakarta.activation:jakarta.activation-api`, so I'd guess switching the server project from `javax.annotation:javax.annotation-api` to `jakarta.annotation:jakarta.annotation-api` shouldn't be too complicated.

**Comment by filipovskid** [comment] 2024-07-02 22:00
@darklore - Great work resolving the issue! It should be okay for closing. @MrPowers

**Comment by MrPowers** [comment] 2024-07-02 22:11
Closing, thanks everyone 😄

**Closed by MrPowers** 2024-07-02 22:11 UTC
